{% set name = "buildbot-console-view" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 540eb1a890630f85e641a6d337c33e3cbbdfac6ec7ab6a28c4286dcf68c04fc0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - buildbot-pkg
    - setuptools
  run:
    - python >={{ python_min }}
    - buildbot-pkg
    - buildbot-www

test:
  imports:
    - buildbot_console_view
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Buildbot Console View plugin
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
