{% set name = "buildbot-console-view" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 712c5952aeda53f8947e44e71fa3212697d17d2115e5dc83a207888ebaa9ea3a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
    - buildbot-pkg
  run:
    - python >3.5
    - buildbot-pkg
    - buildbot-www

test:
  imports:
    - buildbot_console_view
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Buildbot Console View plugin
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
