{% set name = "buildbot-console-view" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 504e2351dd928be12619ae815751e2cb267339dce08ba5eef496be425047b847

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5
    - buildbot-pkg
  run:
    - python >3.5
    - buildbot-pkg
    - buildbot-www

test:
  imports:
    - buildbot_console_view

about:
  home: https://buildbot.net/
  license: GNU General Public (GPL)
  license_family: LGPL
  license_file: LICENSE
  summary: Buildbot Console View plugin
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
