travis:
  secure:
    BINSTAR_TOKEN: fE6w+x+bfeV+JBoAjSXIHGvn/c1L1KYaEfjH+xhW/hl/j+G2iHdOjai8PY9Jf47ZO8DeFifYb2MQNYpnz7sSBuogHRuefRpPDfMkFzsdZ1DqN9Gth341HlMp/TvTvo6P8yTthHrRYqOxhdaTFaiJnHtxCzHO2zywDs9BiFrNnAQ2yuQkuhtrQSBoolGTAuV0TLd0U18shQ8EAmuqsJd6yaUckcfcIVGgKDVW98rRZoaF29VBxOrbKjuQMNtGZtgexd+2UCocD3xvxW/Vz+iwxSojwGD6pZJljuOxU5ku4/y/ThpVkkwE2n3Y7W63NIrpg7MgKB5lpwuDZMmU64dMc0eP/nN6ic0Oz3TpH1AuUg7EXUTBsN0gRclmrzntGkVfEO4uvQsJzvb3vP2eK37ppwoaJlQhIaPwo/P+P3GEMel0PJSXVexdTZ+X0uyTyvkGF8ZFHmuthDVP0u4+REQw5riim8T3lqebUnuy3nfb8tEi2/QXMCNrnJTsNzqbE6h1HTngXR/r1Zd7UqDagCHyLLsz+WFVp2OnUQRAUxqSVO8NsPYUSRAkCy88G0qLzSCQ/fLUZmKYurRTraNRJWTBTSon1cECTU0hjTLz/Mgq2EET6IentS8jCV9rqKhuX3TLPLpQtLJgfunC5VLDzljn4H/BdEJ7xR2znzzCw/qeJn0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
